version: "3.1"

services:
  api:
    build: .
    volumes:
      - .:/app/
    ports: 
        - 3000:3000

  mongo:
    image: mongo
    restart: always
    environment:
        MONGO_INITDB_ROOT_USERNAME: root
        MONGO_INITDB_ROOT_PASSWORD: example
  mosquitto:
    image: eclipse-mosquitto
    ports:
        - 1883:1883
        - 9001:9001
    volumes: 
        - ./mosquitto.conf:/mosquitto/config/mosquitto.conf
  mongo-express:
    image: mongo-express
    logging:
      driver: none
    restart: always
    ports:
        - 8081:8081
    environment:
        ME_CONFIG_MONGODB_ADMINUSERNAME: root
        ME_CONFIG_MONGODB_ADMINPASSWORD: example
